updates:
  - commit-message:
      include: scope
      prefix: fix
    directory: /
    package-ecosystem: docker
    schedule:
      interval: daily
  - commit-message:
      include: scope
      prefix: chore
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: fix
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: weekly
version: 2
